name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*' # Se dispara cuando subes un tag como v1.0.0

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Ejecuta en paralelo para Windows y Linux
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático de GitHub
        run: npm run publish
